/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;

import clases.*;

/**
 *
 * @author Omar
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */

    Jugador jugador;    

    public JugadorPanel() {
        initComponents();
    }

    void SetJugador(Jugador jugador){
        this.jugador = jugador;
        nombre_valor.setText(jugador.getNombre());
        saldo_valor.setText(Float.toString(jugador.getSaldo()));
        rellenaPropiedades(jugador.getPropiedades());
        repaint();
        revalidate();
    }
    private void rellenaPropiedades(ArrayList<Casilla> lista){
        propiedadesPanel.removeAll();
        for(Casilla casilla : lista){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(casilla);
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        // Se actualiza el panel de propiedades y el de jugador
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        nombre_valor = new javax.swing.JTextField();
        Saldo = new javax.swing.JLabel();
        saldo_valor = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setText("Nombre");
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        nombre_valor.setEditable(false);
        nombre_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_valorActionPerformed(evt);
            }
        });
        add(nombre_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        Saldo.setText("Saldo");
        add(Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        saldo_valor.setEditable(false);
        add(saldo_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        propiedadesPanel.setMinimumSize(new java.awt.Dimension(400, 1000));
        propiedadesPanel.setPreferredSize(new java.awt.Dimension(50, 250));
        add(propiedadesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_valorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Saldo;
    private javax.swing.JTextField nombre_valor;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JTextField saldo_valor;
    // End of variables declaration//GEN-END:variables
}
