/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import clases.Casilla;

/**
 *
 * @author Omar
 */
public class PropiedadPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadPanel
     */

    Casilla tituloPropiedad;

    void setPropiedad(Casilla casilla){
        this.tituloPropiedad = casilla;
        nombre.setText(casilla.getNombre());
        NCasas.setText(Float.toString(casilla.getNumCasas()));
        NHoteles.setText(Float.toString(casilla.getNumHoteles()));
        repaint();
    }
    
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        labelCasas = new javax.swing.JLabel();
        NCasas = new javax.swing.JTextField();
        labelHoteles = new javax.swing.JLabel();
        NHoteles = new javax.swing.JTextField();

        lableNombre.setText("Nombre");
        add(lableNombre);

        nombre.setEditable(false);
        add(nombre);

        labelCasas.setText("Nº Casas");
        add(labelCasas);

        NCasas.setEditable(false);
        add(NCasas);

        labelHoteles.setText("Nº Hoteles");
        add(labelHoteles);

        NHoteles.setEditable(false);
        add(NHoteles);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NCasas;
    private javax.swing.JTextField NHoteles;
    private javax.swing.JLabel labelCasas;
    private javax.swing.JLabel labelHoteles;
    private javax.swing.JLabel lableNombre;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
